name: Bug Report
description: Report a bug in BlackRoad OS
labels: ["bug", "triage"]
assignees: ["blackboxprogramming"]
body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report"
  - type: input
    id: component
    attributes:
      label: Component
      placeholder: "e.g., br CLI, CF Worker, Pi tunnel, Alice Pi"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What happened?"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run `br ...`
        2. See error...
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ["Critical (system down)", "High (feature broken)", "Medium (degraded)", "Low (cosmetic)"]
