name: "🐛 Bug Report"
description: Something isn't working as expected
labels: ["type:bug", "status:needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Fill this out as completely as possible.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One sentence describing the bug
      placeholder: "br agents status returns 500 when registry is offline"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to trigger the bug
      placeholder: |
        1. Run `br agents status`
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Should return a graceful error message, not a 500
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Unhandled exception thrown
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "v0.1.0 / commit abc1234"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Logs, screenshots, environment details
