name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
assignees: ["blackboxprogramming"]
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request"
  - type: input
    id: feature
    attributes:
      label: Feature Name
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: "Why is this needed?"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
  - type: dropdown
    id: category
    attributes:
      label: Category
      options: ["CLI Tool", "Agent", "Infrastructure", "UI/Frontend", "Salesforce", "Hardware", "Documentation"]
