name: Feature Request
description: Propose a new feature or improvement
title: "[feat] "
labels: ["enhancement"]
body:
  - type: input
    id: repo
    attributes:
      label: Target Repository
      placeholder: blackroad-core, blackroad-cli, etc.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High — blocks core workflows
        - Medium — quality of life improvement
        - Low — nice to have
    validations:
      required: true
