name: "📋 Task"
description: Internal engineering task or chore
labels: ["status:in-progress"]
body:
  - type: input
    id: summary
    attributes:
      label: Task Summary
      placeholder: "Wire blackroad-agents registry into blackroad-web dashboard"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What does "done" look like?
      placeholder: |
        - [ ] GET /agents endpoint returns live data in dashboard
        - [ ] Error state handled gracefully
        - [ ] Tests passing
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Core / Gateway
        - Agents
        - Web / Dashboard
        - CLI / Operator
        - Infrastructure
        - SDK / API
        - Design System
        - Documentation
        - Hardware / Fleet

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - "XS — < 1 hour"
        - "S — half day"
        - "M — 1 day"
        - "L — 2-3 days"
        - "XL — week+"
